config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :posts do
    get :profile, on: :member
    resources :comments do
      patch :change_status, on: :member
      get :manage_comment, on: :member
    end
  end

  resources :users do
    get :feed, on: :collection
  end

  resources :relationships, only: [:create, :destroy]

  root "posts#index"

  get '/about', to: 'pages#about'
  get '/profile', to: 'pages#profile'
  get '/dashboard', to: 'dashboards#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord

    has_many :comments, dependent: :destroy
    belongs_to :user
    
    validates :title, presence: true, length: { minimum: 5 }
    validates :body, presence: true

    scope :availables, -> { where(status: true) }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts

  has_many :active_relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed

  has_many :passive_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :followed

  def follow(other_user)
    p "a"
    following << other_user unless self == other_user
    p "a---------"
    p following
  end

  def unfollow(other_user)
    following.delete(other_user)
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def feed
    Post.where("user_id IN (?)", following_ids).availables
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.new(comment_params)
		@comment.user_id = current_user.id
		@comment.save
		
		respond_to do |format|
      format.html { redirect_to post_path(@post) }
      format.js
    end
	end


	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy!

		respond_to do |format|
      format.html { redirect_to post_path(@post) }
      format.js
    end
		
	end

	def change_status
    @post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])

    @comment.update!(status: params[:status])

    redirect_to post_path(@post)
  end

	def manage_comment
		@post = Post.find(params[:id])
		p "sdsa"
	end

	private

	def comment_params
    params.require(:comment).permit(:name, :body)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  def index
    @posts = Post.where(user_id: current_user.id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def about
    @user = User.find(current_user.id)
    @posts = Post.where(user_id: @user.id)
    @comments = Comment.where(user_id: @user.id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@posts = Post.where(status: true).order('created_at DESC')
	end

	def new
		@post = Post.new
	end

	def show
		set_post
	end

	def create
		@post = Post.new(post_params)
		@post.user_id = current_user.id

		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def edit
		set_post
	end

	def update
		set_post

		if @post.update(post_params)
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		set_post
		@post.destroy

		redirect_to posts_path
	end

	def profile
		set_post
		@posts = Post.where(user_id: @post.user_id, visible: true)

		@posts = Post.where(user_id: @post.user_id) if @post.user_id == current_user.id
		@my_profile = true if @post.user_id == current_user.id

		@user = User.find(@post.user_id)

	end

	private

	def set_post
		@post = Post.find(params[:id])
	end

	def post_params
		params.require(:post).permit(:title, :body, :status)
	end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!

  def create
    @user = User.find(params[:followed_id])
    current_user.follow(@user)

    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end

  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow(@user)

    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = User.find(params[:id])
    @posts = Post.where(user_id: @user.id, status: true)
  end

  def feed
    @posts = current_user.feed
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def my_comment?(current_user, comment_user_id)
    current_user.id == comment_user_id
  end

  def my_post(current_user, post_user_id)
    current_user.id == post_user_id
  end

  def comment_time_past?(comment)
    (Time.now - (2.day)) > comment.created_at
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<% if comment.status == "accepted" %>
	<div class="comment clearfix">
		<div class="comment_content">
			<p class="comment_name"><strong><%= comment.name %></strong></p>
			<p class="comment_body"><%= comment.body %></p>
			<p class="comment_time"><%= time_ago_in_words(comment.created_at) %> Ago</p>
		</div>
	</div>
<% end %>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build], remote: true) do |f| %>
	<%= f.label :name %><br>
	<%= f.text_field :name %><br>
	<br>
	<%= f.label :body %><br>
	<%= f.text_area :body %><br>
	<br>
	<%= f.submit %>
<% end %>

app/views/comments/create.js.erb
$('#comment_count').html("<h2><%= @post.comments.count %> Comments</h2>");

app/views/comments/destroy.js.erb
$('#comment_<% @comment.id%>').remove();

app/views/comments/manage_comment.html.erb
<% @post.comments.each do |comment|%>
	<div id="comment_content" class="">
		<h1 class="title"><%= comment.name %></h1>
		<p class="date">
			Submitted <%= time_ago_in_words(comment.created_at) %> Ago
			<% if user_signed_in? %>
				<p>
				<% if comment.status == "accepted" %>
					<%= link_to 'Deny', change_status_post_comment_path(comment.post, comment, status: "denied"), method: :patch, class: "button" if my_comment?(current_user, comment.user_id) && comment_time_past?(comment) %>
				<% else  %>								
					<%= link_to 'Accept', change_status_post_comment_path(comment.post, comment, status: "accepted"), method: :patch, class: "button" if my_comment?(current_user, comment.user_id) && comment_time_past?(comment) %>
				<% end %>
				</p>
			<% end %>
		</p>
	</div>
<% end %>

app/views/dashboards/index.html.erb
<% @posts.each do |post| %>
	<div class="post_wrapper">
		<h2 class="title"><%= link_to post.title, post %></h2>
		<p class="date"><%= post.body.truncate(100) %></p>
		<p class="date"><%= post.created_at.strftime("%B %d, %Y") %></p>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MeyBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
	<div id="sidebar">
		<div id="logo">
			<%= link_to root_path do %>
				<%#= image_tag "logo.svg" %>
			<% end %>
		</div>
<% if user_signed_in? %>
		<ul>
			<li class="category">Website</li>
			<li><%= link_to "Blog", feed_users_path %></li>
			<li><%= link_to "Profile", about_path %></li>
		</ul>
<% end %>

		<% if !user_signed_in? %>
			<p class="sign_in"><%= link_to "Admin Login", new_user_session_path %></p>
		<% end %>
	</div>

	<div id="main_content">
		<div id="header">
		<% if user_signed_in? %>
			<% if current_page?(root_path) %>
				<p>All Posts</p>
			<% elsif current_page?(about_path) %>
				<p>Profile</p>
			<% else %>
				<%= link_to "Back to All Posts", root_path %>
			<% end %>
		<% end %>

			<% if user_signed_in? %>
				<div class="buttons">
					<button class="button"><%= link_to "New Post", new_post_path %></button>
					<button class="button"><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></button>
				</div>
			<% else %>
				<div class="buttons">
					<button class="button"><%= link_to 'Sign In', new_user_session_path %></button>
					<button class="button"><%= link_to 'Sign Up', new_user_registration_path %></button>
				</div>
			<% end %>
		</div>

		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert") %>
		<% end %>
			<%= yield %>

	</div>
</body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
	<div id="profile_image">
		<%#= image_tag "a.jpeg" %>
	</div>

	<div id="content">
		<p>Name: <%= @user.email.split('@').first %></p>
		<p>Name: <%= @user.email %></p>
		<p>Joined at <%= @user.created_at.strftime("%B %d, %Y") %></p>
  
			<%= link_to 'edit', edit_user_registration_path(@user), class: "button"  if @my_profile = true %> </p>
	</div>
</div>

<div id="page_wrapper">
	<div id="content">
		<div class="post_wrapper">
			<h1 class="title"></h1>
		</div>
		<div class="post_wrapper">
			<h1 class="title">Posts</h1>
		</div>
		<% @posts.each do |post| %>
			<div class="post_wrapper">
				<p class="title"><%= link_to post.title, post %></p>
				<p class="date"><%= post.created_at.strftime("%B %d, %Y") %></p>
			</div>
		<% end %>
		<div class="post_wrapper">
			<h1 class="title">Comments</h1>
		</div>
		<% @comments.each do |comment| %>
			<div class="post_wrapper" id="comment_<% comment.id %>">
				<p class="title">Name: <%= comment.name %></p>
				<p class="title">Post Name: <%= comment.post.title %></p>
				<p class="title">Status: <%= comment.status %></p>
				<p class="date">Created at: <%= comment.created_at.strftime("%B %d, %Y") %></p>
				<p><%= link_to 'Delete', [comment.post, comment], method: :delete, remote: true, class: "button", data: { confirm: 'Are you sure?' } if my_comment?(current_user, comment.user_id) || my_post(current_user, comment.post.user_id) %>
			</div>
		<% end %>
	</div>	
</div>

app/views/pages/index.html.erb
<div id="profile">
		<h1 class="title"><%= user.name %></h1>
		<p class="date">
			Joined <%= user.created_at %>
			<% if user_signed_in? %>
				<%= render "pages/profile_content" %>
			<% end %>
		</p>
	</div>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
		<div id="errors">
			<h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving:</h2>
			<ul>
				<% @post.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<%= f.label :title %><br>
	<%= f.text_field :title %><br>
	<br>
	<%= f.label :body %><br>
	<%= f.text_field :body %><br>
	<br>
	<%= f.label :Visible %><br>
	<%= f.check_box :status %><br>
	<br>
	<%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
	<h1>Edit Post</h1>

	<%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% if user_signed_in? %>
	<% @posts.each do |post| %>
		<div class="post_wrapper">
			<h2 class="title"><%= link_to post.title, post %></h2>
			<p class="date"><%= post.created_at.strftime("%B %d, %Y") %></p>
		</div>
	<% end %>
<% else %>
	<div class="post_wrapper">
		<h2 class="title">WELCOME</h2>
	</div>
<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
	<h1>New Post</h1>

	<%= render 'form' %>
</div>

app/views/posts/profile.html.erb
<div id="page_wrapper">
	<div id="profile_image">
		<%#= image_tag "a.jpeg" %>
	</div>

	<div id="content">
		<p>Name: <%= @user.email.split('@').first %></p>
		<p>Name: <%= @user.email %></p>
		<p>Joined at <%= @user.created_at.strftime("%B %d, %Y") %></p>

			<div id='followers'>
			<b>Following(<%= @user.following.count %>)</b>
			<b>Follower(<%= @user.followers.count %>)</b>
		</div>

		<% if user_signed_in? && @user == current_user %>
			<p><%= render 'users/follow_form' %></p>
		<% end %>   
			<%= link_to 'edit', edit_user_registration_path(@user), class: "button"  if @my_profile = true %> </p>
	</div>
</div>

<div id="page_wrapper">
	<div id="content">
		<div class="post_wrapper">
			<h1 class="title"></h1>
		</div>
		<div class="post_wrapper">
			<h1 class="title">Posts</h1>
		</div>
		<% @posts.each do |post| %>
			<div class="post_wrapper">
				<p class="title"><%= link_to post.title, post %></p>
				<p class="date"><%= post.created_at.strftime("%B %d, %Y") %></p>
			</div>
		<% end %>
	</div>	
</div>

app/views/posts/show.html.erb
<div id="post_content">
	<h1 class="title"><%= @post.title %></h1>
	<p class="date">
	<%= link_to @post.user.email.split('@').first, user_path(@post.user) %>	Submitted <%= time_ago_in_words(@post.created_at) %> Ago
		<% if user_signed_in? && my_post(current_user, @post.user_id)%>
		| <%= link_to 'Edit', edit_post_path(@post) %> |
		  <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %>
	 |	<%= link_to 'Manage Comments', manage_comment_post_comment_path(post_id: @post) %>
	  <% end %>
	</p>
	<div id="content">
		<p class="body"><%= @post.body %></p>
	</div>
	<div id="comments">
		<div id="comment_count"><h2><%= @post.comments.count %> Comments</h2></div>
		<%= render @post.comments %>
	</div>
	<div id="comments_form">
		<h3>Add a comment:</h3>
		<%= render "comments/form" %>
	</div>
</div>

app/views/relationships/create.js.erb
$('#follow_form').html("<%= escape_javascript(render('users/unfollow')) %>");
$('#followers').html("<b>Following(<%= @user.following.count %>)</b> <b>Follower(<%= @user.followers.count %>)</b>");

app/views/relationships/destroy.js.erb
$('#follow_form').html("<%= escape_javascript(render('users/follow')) %>");
$('#followers').html("<b>Following(<%= @user.following.count %>)</b> <b>Follower(<%= @user.followers.count %>)</b>");

app/views/users/_follow.html.erb
<%= form_with(model: current_user.active_relationships.build, local: false) do |f| %>
  <%= hidden_field_tag :followed_id, @user.id %>
  <%= f.submit 'Follow' %>
<% end %>

app/views/users/_follow_form.html.erb
<div id='follow_form'>
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
</div>

app/views/users/_unfollow.html.erb
<%= form_with(model: current_user.active_relationships.find_by(followed_id: @user.id),
              html: { method: :delete }, local: false) do |f| %>
  <%= f.submit 'Unfollow' %>
<% end %>

app/views/users/feed.html.erb
<% if user_signed_in? %>
	<% @posts.each do |post| %>
		<div class="post_wrapper">
			<h2 class="title"><%= link_to post.title, post %></h2>
			<p class="date"><%= post.created_at.strftime("%B %d, %Y") %></p>
		</div>
	<% end %>
<% else %>
	<div class="post_wrapper">
		<h2 class="title">WELCOME</h2>
	</div>
<% end %>

app/views/users/show.html.erb
<div id="page_wrapper">
	<div id="profile_image">
		<%#= image_tag "a.jpeg" %>
	</div>

	<div id="content">
		<p>Name: <%= @user.email.split('@').first %></p>
		<p>Name: <%= @user.email %></p>
		<p>Joined at <%= @user.created_at.strftime("%B %d, %Y") %></p>

		<div id="followers">
			<b>Following(<%= @user.following.count %>)</b>
			<b>Follower(<%= @user.followers.count %>)</b>
		</div>

		<% if user_signed_in? && @user != current_user %>
			<p><%= render 'follow_form' %></p>
		<% end %>
	</div>
</div>

<div id="page_wrapper">
	<div id="content">
		<div class="post_wrapper">
			<h1 class="title"></h1>
		</div>
		<div class="post_wrapper">
			<h1 class="title">Posts</h1>
		</div>
		<% @posts.each do |post| %>
			<div class="post_wrapper">
				<p class="title"><%= link_to post.title, post %></p>
				<p class="date"><%= post.created_at.strftime("%B %d, %Y") %></p>
			</div>
		<% end %>
	</div>	
</div>